### ISSUE TITLE
Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by adebali** [veg/phylotree.js#107]
I run `npm install` followed by `yarn run develop`. I can see the application through web browser. However, it is not functional. Data can't be loaded. Could you help me understand the following error?

```
$ yarn run develop
yarn run v0.20.3
$ concurrently "webpack --watch --mode=development" "http-server"
[0] /Users/ogunadebali/Repositories/phylotree.js/node_modules/webpack-cli/bin/config-yargs.js:89
[0] 				describe: optionsSchema.definitions.output.properties.path.description,
[0] 				                                           ^
[0]
[0] TypeError: Cannot read property 'properties' of undefined
[0]     at module.exports (/Users/ogunadebali/Repositories/phylotree.js/node_modules/webpack-cli/bin/config-yargs.js:89:48)
[0]     at /Users/ogunadebali/Repositories/phylotree.js/node_modules/webpack-cli/bin/webpack.js:60:27
[0]     at Object.<anonymous> (/Users/ogunadebali/Repositories/phylotree.js/node_modules/webpack-cli/bin/webpack.js:515:3)
[0]     at Module._compile (internal/modules/cjs/loader.js:688:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
[0]     at Module.load (internal/modules/cjs/loader.js:598:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[0]     at Module.require (internal/modules/cjs/loader.js:636:17)
[0]     at require (internal/modules/cjs/helpers.js:20:18)
[0] webpack --watch --mode=development exited with code 1
[1] Starting up http-server, serving ./
[1] Available on:
[1]   http://127.0.0.1:8080
```

**Comment by stephenshank** [comment]
Dear @adebali,

I've confirmed the behavior you describe. Can you please try installing [yarn](https://yarnpkg.com/en/) and running `yarn install` instead of `npm install`, and try again?

Best,
Stephen

**Comment by adebali** [comment]
I tried here is the output now:

```
yarn install v0.20.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by stephenshank** [comment]
What does `node --version` return?

**Comment by adebali** [comment]
Yeah, it was `v10.12.0`. Node `9.0` works. Thanks!
